spring:
  application:
    name: TicketService
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6432/testdb}
    username: ${SPRING_DATASOURCE_USERNAME:testpguser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpgpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

springdoc:
  #api-docs:
  #path: /v2/api-docs
  show-actuator: false
  swagger-ui:
    enabled: true
    #    oauth:
    #      use-basic-auth-with-access-code-flow: true
    #path: /swagger-ui.html

server:
  port: 9000
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

